/**
 * how to generate this list
 * out = []
 * outStr = []
 * $('.page').querySelectorAll('.box h3:first-of-type').forEach(ele => out.push(ele))
 * out.forEach(ele => outStr.push(ele.innerHTML))
 */


let list = [
    "Flexport",
    "Newfront",
    "Blend",
    "Clearbit",
    "Bolt",
    "Airtable",
    "Ubiquity6",
    "Atrium",
    "Reserve",
    "comma",
    "Amplitude",
    "Lever",
    "Neuralink",
    "Qualia",
    "DeepMind",
    "Grail",
    "Voyage",
    "Freshworks",
    "Demisto",
    "Rippling",
    "Even",
    "DeepMap",
    "Chime Bank",
    "Boring Company",
    "Theorem LP",
    "Superhuman",
    "Chronicle Security",
    "Pinterest",
    "Leanplum",
    "Lambda School",
    "ConsenSys",
    "Harbor",
    "Kitty Hawk",
    "Obsidian Security",
    "OneWeb",
    "LessWrong",
    "SpaceX and Blue Origin",
    "G2 Crowd",
    "Petuum",
    "Applied Intuition",
    "Curai",
    "Samsara",
    "Podium",
    "Zoom",
    "Canopy",
    "Mixmax",
    "Freenome",
    "Stripe",
    "Illumio",
    "Bird",
    "Rubrik",
    "Chan Zuckerberg Initiative",
    "Magic Leap",
    "Uber ATG",
    "Lime",
    "Snowflake Computing",
    "Mapbox",
    "Fortem Technologies",
    "Brain Corp",
    "Scalyr",
    "Airkit",
    "Virta",
    "Saildrone",
    "Sourcegraph",
    "Andela",
    "Asana",
    "Density",
    "SalesLoft",
    "Tinder",
    "Humu",
    "Algolia",
    "Lab126",
    "Asteroid Technologies",
    "Discord",
    "Coinbase",
    "Lattice",
    "Scale API",
    "Autonomous Trucking",
    "Culture Amp",
    "DingTalk",
    "Thalmic Labs",
    "Intercom",
    "JUUL",
    "Plaid",
    "Amazon Web Services",
    "Shogun",
    "Confluent",
    "FreightWaves",
    "Cohesity",
    "Carta",
    "Elastic",
    "Rover",
    "Signal",
    "Robinhood",
    "Zcash",
    "Recursion Pharmaceuticals",
    "Vicarious",
    "Nuro",
    "Siri",
    "Brex",
    "Waymo",
    "AngelList",
    "Gitlab",
    "Protocol Labs",
    "Razorpay",
    "Career Advice: Dream Jobs",
    "Cruise",
    "Zoox",
    "23andMe",
    "UiPath",
    "Tala",
    "Front",
    "Sonder",
    "One Concern",
    "N3twork",
    "Reddit",
    "Roofstock",
    "LiDAR Companies",
    "Alice Technologies",
    "Triplebyte",
    "Oculus",
    "Cloudbees",
    "Uber Eats",
    "Lemonade",
    "Zapier",
    "SafeGraph",
    "Katerra",
    "CTRL-Labs",
    "Datadog",
    "Binance",
    "Justworks",
    "Goat",
    "Numerai",
    "Pendo.io",
    "Iterable",
    "Tesla Self-Driving Team",
    "RideOS",
    "Nauto",
    "Instacart",
    "HashiCorp",
    "Niantic",
    "Landing.ai",
    "Career Advice: Hiring is Failure",
    "Wealthfront",
    "Opendoor",
    "TripActions",
    "Drift",
    "Shone",
    "Starship Technologies",
    "Lightstep",
    "FlyHomes",
    "Reality Glasses at Apple",
    "Rappi",
    "Joby Aviation",
    "Convoy",
    "Cresta",
    "Rival",
    "Quora",
    "Google Home",
    "Stablecoins",
    "Databricks",
    "Checkr",
    "Acorns",
    "Aurora",
    "Boom Supersonic",
    "Domino Data Lab",
    "Rigetti",
    "Affirm",
    "Harness",
    "Forward",
    "Affinity",
    "Sensei",
    "Google Cloud",
    "Envoy",
    "Astranis",
    "InVision",
    "ThoughtSpot",
    "Notion",
    "Gusto",
    "Cloudflare",
    "Slack",
    "OpenAI",
    "X (Alphabet Moonshots)",
    "At-Bay",
    "Lyric",
    "CoinList",
    "KaiOS",
    "CrowdStrike",
    "DoorDash",
    "Segment",
    "Lyft",
    "Sandbox VR",
    "SeatGeek",
    "Looker",
    "Echo (Alexa)",
    "Color",
    "Anduril"
]

function isBLCo(blk) {
    let bool = false;
    let matchCo;
    list.some(co => {
        let re = new RegExp(co, 'gi')
        if (blk && blk.substring(0, 11+co.length+1).match(re)) {
            let str = blk.split('\n')[2];
            if (str) str = str.substring(0, str.indexOf('|'));
            if (str) str.trim();
            
            if (str && co && str.length === co.length) {
                matchCo = co;
                bool = true;
                return;
            }
        }
    })
    return bool ? matchCo : false;
}

module.exports = isBLCo;
